<?php
/**
 * HLS Handler — REST API endpoints for HLS manifests and segments.
 *
 * Registers routes for serving the master playlist, variant playlists, and
 * .ts segment files generated by the compressor. All paths are validated
 * through VSB_Video_Helper to prevent traversal attacks.
 *
 * SECURITY NOTES:
 *
 * - The handler verifies that the attachment exists and is a valid video
 *   via VSB_Video_Helper before serving any HLS data.
 * - Segment filenames are validated against a strict pattern to prevent
 *   path traversal (only alphanumeric, dashes, dots, and %-encoding).
 * - All file access is contained within the vsb-compressed directory
 *   under wp-content/uploads.
 *
 * @package VideoStreamBuffer
 * @since   2.0.0
 */

// Prevent direct access.
defined( 'ABSPATH' ) || exit;

class VSB_HLS_Handler {

	/**
	 * Register the HLS REST API routes.
	 *
	 * @since 2.0.0
	 */
	public static function register_routes() {
		// Master playlist: .../hls/{id}/master.m3u8
		register_rest_route(
			'video-stream/v1',
			'/hls/(?P<attachment_id>\d+)/master\.m3u8',
			array(
				'methods'             => 'GET',
				'callback'            => array( __CLASS__, 'serve_master_playlist' ),
				'permission_callback' => array( __CLASS__, 'check_permission' ),
				'args'                => array(
					'attachment_id' => array(
						'required'          => true,
						'validate_callback' => function ( $param ) {
							return absint( $param ) > 0;
						},
						'sanitize_callback' => 'absint',
					),
				),
			)
		);

		// Variant playlist: .../hls/{id}/{variant}.m3u8
		register_rest_route(
			'video-stream/v1',
			'/hls/(?P<attachment_id>\d+)/(?P<variant>[a-zA-Z0-9\-]+)\.m3u8',
			array(
				'methods'             => 'GET',
				'callback'            => array( __CLASS__, 'serve_variant_playlist' ),
				'permission_callback' => array( __CLASS__, 'check_permission' ),
				'args'                => array(
					'attachment_id' => array(
						'required'          => true,
						'validate_callback' => function ( $param ) {
							return absint( $param ) > 0;
						},
						'sanitize_callback' => 'absint',
					),
					'variant' => array(
						'required'          => true,
						'validate_callback' => function ( $param ) {
							return (bool) preg_match( '/^[a-zA-Z0-9\-]+$/', $param );
						},
						'sanitize_callback' => function ( $param ) {
							return preg_replace( '/[^a-zA-Z0-9\-]/', '', $param );
						},
					),
				),
			)
		);

		// Segment files: .../hls/{id}/{filename}.ts
		// Filename may contain variant name prefix like "vsb-1080p-001.ts".
		register_rest_route(
			'video-stream/v1',
			'/hls/(?P<attachment_id>\d+)/(?P<filename>[a-zA-Z0-9\-\_\%]+\.ts)',
			array(
				'methods'             => 'GET',
				'callback'            => array( __CLASS__, 'serve_segment' ),
				'permission_callback' => array( __CLASS__, 'check_permission' ),
				'args'                => array(
					'attachment_id' => array(
						'required'          => true,
						'validate_callback' => function ( $param ) {
							return absint( $param ) > 0;
						},
						'sanitize_callback' => 'absint',
					),
					'filename' => array(
						'required'          => true,
						'validate_callback' => function ( $param ) {
							// Only allow safe segment filenames: vsb-{variant}-{num}.ts
							return (bool) preg_match( '/^[a-zA-Z0-9\-\_\%]+\.ts$/', $param );
						},
						'sanitize_callback' => function ( $param ) {
							return preg_replace( '/[^a-zA-Z0-9\-\_\%\.]/', '', $param );
						},
					),
				),
			)
		);
	}

	/**
	 * Permission callback — same logic as the stream handler.
	 *
	 * @since  2.0.0
	 * @param  WP_REST_Request $request The current request.
	 * @return bool|WP_Error
	 */
	public static function check_permission( $request ) {
		$restrict = get_option( 'vsb_restrict_logged_in', false );

		if ( $restrict && ! is_user_logged_in() ) {
			return new WP_Error(
				'vsb_restricted',
				__( 'You must be logged in to stream videos.', 'video-stream-buffer' ),
				array( 'status' => 401 )
			);
		}

		return true;
	}

	/**
	 * Validate the attachment and return the HLS base directory.
	 *
	 * This is the shared security boundary — all HLS serving methods go
	 * through this to ensure the attachment is valid and the compressed
	 * directory exists.
	 *
	 * @since  2.0.0
	 * @param  int $attachment_id Attachment ID.
	 * @return string|WP_Error Absolute path to the HLS directory, or error.
	 */
	private static function validate_and_get_hls_dir( $attachment_id ) {
		$attachment_id = absint( $attachment_id );

		// Validate via the shared video helper.
		$video = VSB_Video_Helper::get_video_by_attachment_id( $attachment_id );
		if ( is_wp_error( $video ) ) {
			return $video;
		}

		// Check if compressed.
		if ( ! VSB_Compressor::is_compressed( $attachment_id ) ) {
			return new WP_Error(
				'vsb_not_compressed',
				__( 'This video has not been compressed for HLS streaming.', 'video-stream-buffer' ),
				array( 'status' => 404 )
			);
		}

		// Get the output directory.
		$output_dir = get_post_meta( $attachment_id, '_vsb_hls_dir', true );
		if ( empty( $output_dir ) || ! is_dir( $output_dir ) ) {
			return new WP_Error(
				'vsb_hls_dir_missing',
				__( 'HLS data directory not found. The video may need to be recompressed.', 'video-stream-buffer' ),
				array( 'status' => 404 )
			);
		}

		// PATH TRAVERSAL DEFENSE: resolve real paths and verify containment
		// within the uploads-basedir/vsb-compressed hierarchy.
		$real_dir = realpath( $output_dir );
		if ( false === $real_dir ) {
			return new WP_Error(
				'vsb_path_error',
				__( 'Could not resolve HLS directory path.', 'video-stream-buffer' ),
				array( 'status' => 500 )
			);
		}

		$upload_dir     = wp_upload_dir();
		$upload_basedir = realpath( $upload_dir['basedir'] );
		$compressed_dir = $upload_basedir . DIRECTORY_SEPARATOR . 'vsb-compressed';

		if ( 0 !== strpos( $real_dir, $compressed_dir ) ) {
			if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
				error_log(
					sprintf(
						'[Video Stream Buffer] HLS path traversal attempt blocked for attachment %d.',
						$attachment_id
					)
				);
			}
			return new WP_Error(
				'vsb_path_traversal',
				__( 'Invalid HLS file location.', 'video-stream-buffer' ),
				array( 'status' => 403 )
			);
		}

		return $real_dir;
	}

	/**
	 * Serve the master playlist (master.m3u8).
	 *
	 * @since  2.0.0
	 * @param  WP_REST_Request $request REST request.
	 * @return WP_Error|void Exits on success.
	 */
	public static function serve_master_playlist( $request ) {
		$attachment_id = $request->get_param( 'attachment_id' );
		$hls_dir       = self::validate_and_get_hls_dir( $attachment_id );

		if ( is_wp_error( $hls_dir ) ) {
			return $hls_dir;
		}

		$master_file = $hls_dir . '/master.m3u8';

		if ( ! file_exists( $master_file ) ) {
			return new WP_Error(
				'vsb_master_missing',
				__( 'Master playlist not found.', 'video-stream-buffer' ),
				array( 'status' => 404 )
			);
		}

		// Read the master playlist and replace relative URLs with REST URLs.
		$content = file_get_contents( $master_file );
		if ( false === $content ) {
			return new WP_Error(
				'vsb_read_failed',
				__( 'Could not read master playlist.', 'video-stream-buffer' ),
				array( 'status' => 500 )
			);
		}

		// Rewrite relative playlist URLs to our REST endpoints.
		// Lines that are not #EXT... and end with .m3u8 are playlist file references.
		$base_url = rest_url( 'video-stream/v1/hls/' . absint( $attachment_id ) . '/' );
		$lines    = explode( "\n", $content );
		foreach ( $lines as &$line ) {
			$trimmed = trim( $line );
			if ( '' === $trimmed || '#' === $trimmed[0] ) {
				continue;
			}
			if ( '.m3u8' === substr( $trimmed, -5 ) ) {
				$line = $base_url . $trimmed;
			}
		}
		unset( $line );
		$content = implode( "\n", $lines );

		$headers = array(
			'Content-Type'  => 'application/vnd.apple.mpegurl',
			'Cache-Control' => 'public, max-age=3600',
		);

		// Also send as application/x-mpegURL for broader compatibility.
		header( 'Content-Type: application/vnd.apple.mpegurl' );
		header( 'Content-Type: application/x-mpegURL' );
		header( 'Cache-Control: public, max-age=3600' );
		header( 'Access-Control-Allow-Origin: *' );
		header( 'X-Content-Type-Options: nosniff' );

		echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped — playlist text.
		exit;
	}

	/**
	 * Serve a variant playlist (e.g., vsb-720p.m3u8).
	 *
	 * @since  2.0.0
	 * @param  WP_REST_Request $request REST request.
	 * @return WP_Error|void Exits on success.
	 */
	public static function serve_variant_playlist( $request ) {
		$attachment_id = $request->get_param( 'attachment_id' );
		$variant       = $request->get_param( 'variant' );
		$hls_dir       = self::validate_and_get_hls_dir( $attachment_id );

		if ( is_wp_error( $hls_dir ) ) {
			return $hls_dir;
		}

		$variant_file = $hls_dir . '/' . $variant . '.m3u8';

		// PATH TRAVERSAL: verify the resolved file is within the HLS dir.
		$real_file = realpath( $variant_file );
		if ( false === $real_file || 0 !== strpos( $real_file, $hls_dir ) ) {
			return new WP_Error(
				'vsb_invalid_variant',
				__( 'Invalid variant playlist requested.', 'video-stream-buffer' ),
				array( 'status' => 403 )
			);
		}

		if ( ! file_exists( $real_file ) ) {
			return new WP_Error(
				'vsb_variant_missing',
				__( 'Variant playlist not found.', 'video-stream-buffer' ),
				array( 'status' => 404 )
			);
		}

		$content = file_get_contents( $real_file );
		if ( false === $content ) {
			return new WP_Error(
				'vsb_read_failed',
				__( 'Could not read variant playlist.', 'video-stream-buffer' ),
				array( 'status' => 500 )
			);
		}

		// Rewrite segment URLs to point to our REST endpoint.
		$segment_base = rest_url( 'video-stream/v1/hls/' . absint( $attachment_id ) . '/' );
		$lines = explode( "\n", $content );
		foreach ( $lines as &$line ) {
			$trimmed = trim( $line );
			if ( '' === $trimmed || '#' === $trimmed[0] ) {
				continue;
			}
			if ( '.ts' === substr( $trimmed, -3 ) ) {
				$line = $segment_base . $trimmed;
			}
		}
		unset( $line );
		$content = implode( "\n", $lines );

		header( 'Content-Type: application/vnd.apple.mpegurl' );
		header( 'Cache-Control: public, max-age=3600' );
		header( 'Access-Control-Allow-Origin: *' );
		header( 'X-Content-Type-Options: nosniff' );

		echo $content; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
		exit;
	}

	/**
	 * Serve an HLS segment (.ts file).
	 *
	 * Supports HTTP Range requests for seeking within segments.
	 *
	 * @since  2.0.0
	 * @param  WP_REST_Request $request REST request.
	 * @return WP_Error|void Exits on success.
	 */
	public static function serve_segment( $request ) {
		$attachment_id = $request->get_param( 'attachment_id' );
		$filename      = $request->get_param( 'filename' );
		$hls_dir       = self::validate_and_get_hls_dir( $attachment_id );

		if ( is_wp_error( $hls_dir ) ) {
			return $hls_dir;
		}

		$segment_file = $hls_dir . '/' . $filename;

		// PATH TRAVERSAL: verify the resolved file is within the HLS dir.
		$real_file = realpath( $segment_file );
		if ( false === $real_file || 0 !== strpos( $real_file, $hls_dir ) ) {
			return new WP_Error(
				'vsb_invalid_segment',
				__( 'Invalid segment requested.', 'video-stream-buffer' ),
				array( 'status' => 403 )
			);
		}

		if ( ! file_exists( $real_file ) ) {
			return new WP_Error(
				'vsb_segment_missing',
				__( 'Segment file not found.', 'video-stream-buffer' ),
				array( 'status' => 404 )
			);
		}

		$file_size = filesize( $real_file );
		$file_handle = fopen( $real_file, 'rb' );

		if ( ! $file_handle ) {
			return new WP_Error(
				'vsb_fopen_failed',
				__( 'Could not open segment file.', 'video-stream-buffer' ),
				array( 'status' => 500 )
			);
		}

		set_time_limit( 0 );

		$chunk_size = 65536; // 64 KB chunk for TS segments (typically small).

		// Support Range requests for seeking within segments.
		if ( isset( $_SERVER['HTTP_RANGE'] ) ) {
			$range_header = $_SERVER['HTTP_RANGE'];

			if ( preg_match( '/bytes=(\d+)-(\d*)/', $range_header, $matches ) ) {
				$range_start = intval( $matches[1] );
				$range_end   = ( '' !== $matches[2] ) ? intval( $matches[2] ) : ( $file_size - 1 );

				if ( $range_start > $range_end || $range_start >= $file_size ) {
					header( 'HTTP/1.1 416 Range Not Satisfiable' );
					header( 'Content-Range: bytes */' . $file_size );
					fclose( $file_handle );
					exit;
				}

				if ( $range_end >= $file_size ) {
					$range_end = $file_size - 1;
				}

				$content_length = $range_end - $range_start + 1;
				fseek( $file_handle, $range_start );

				header( 'HTTP/1.1 206 Partial Content' );
				header( 'Content-Type: video/mp2t' );
				header( 'Content-Length: ' . $content_length );
				header( 'Content-Range: bytes ' . $range_start . '-' . $range_end . '/' . $file_size );
				header( 'Accept-Ranges: bytes' );
				header( 'Cache-Control: public, max-age=86400' );
				header( 'Access-Control-Allow-Origin: *' );

				$bytes_remaining = $content_length;
				while ( $bytes_remaining > 0 && ! feof( $file_handle ) ) {
					$read_size = min( $chunk_size, $bytes_remaining );
					$buffer    = fread( $file_handle, $read_size );
					if ( false === $buffer ) {
						break;
					}
					echo $buffer; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped — binary data.
					$bytes_remaining -= strlen( $buffer );
					if ( ob_get_level() ) {
						ob_flush();
					}
					flush();
				}
				fclose( $file_handle );
				exit;
			}
		}

		// Full segment (no Range header).
		header( 'HTTP/1.1 200 OK' );
		header( 'Content-Type: video/mp2t' );
		header( 'Content-Length: ' . $file_size );
		header( 'Accept-Ranges: bytes' );
		header( 'Cache-Control: public, max-age=86400' );
		header( 'Access-Control-Allow-Origin: *' );
		header( 'X-Content-Type-Options: nosniff' );

		while ( ! feof( $file_handle ) ) {
			$buffer = fread( $file_handle, $chunk_size );
			if ( false === $buffer ) {
				break;
			}
			echo $buffer; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
			if ( ob_get_level() ) {
				ob_flush();
			}
			flush();
		}

		fclose( $file_handle );
		exit;
	}
}
